### ISSUE TITLE
rux-button icon variant no longer displays

### ISSUE THREAD

**Issue by nortonprojects** [RocketCommunicationsInc/astro#1027]
**To Reproduce**

1. Go to https://astro-components.netlify.app/?path=/docs/components-button--with-slotted-icon

**Current behavior**
Icon button doesn't display

**Expected behavior**
Icon button should display

**Comment by micahjones13** [comment]
I'm not seeing the icon missing? https://astro-components.netlify.app/?path=/docs/components-button--with-slotted-icon#with-slotted-icon

**Comment by micahjones13** [comment]
Sorry - try this link https://astro-components.netlify.app/?path=/docs/components-button--with-slotted-icon#with-slotted-icon

**Comment by nortonprojects** [comment]
I'm seeing it now too, it must have been a caching issue or something from the release.
