### ISSUE TITLE
RuxInput react component does not immediately update with state change

### ISSUE THREAD

**Issue by 321github123** [RocketCommunicationsInc/astro#105]
Hi,

Here is a link to a very basic RuxInput button.

https://codesandbox.io/embed/priceless-moser-nc9p7?fontsize=14&hidenavigation=1&theme=dark

If I a type a long name (longer than 8 characters), the state does not automatically update to the error message unless I tab out.

![exampe_bug](https://user-images.githubusercontent.com/94007578/140983025-38b03251-36eb-41bb-84e0-1d460750a32d.png)

```javascript
import React from "react";
import { RuxInput } from "@astrouxds/react";

export default class App extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      firstName: "John"
    };
  }

  onChange = (e) => {
    if (e.target.value.length > 8) {
      this.setState({ [e.target.name]: "too long!!!" });
    } else {
      this.setState({ [e.target.name]: e.target.value });
    }
  };

  render() {
    return (
      <form onSubmit={this.handleSubmit}>
        <RuxInput
          label="First Name:"
          name="firstName"
          type="text"
          onRuxchange={this.onChange}
          value={this.state.firstName}
          required={true}
        />
      </form>
    );
  }
}
```

**Comment by micahjones13** [comment]
Hey there, 

The issue here is that onRuxchange doesn't fire until focus is lost, as per the vanilla functionality of the [HTML change event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event). This is opposite in React, where [onChange fires with each user input](https://reactjs.org/docs/dom-elements.html#onchange). 
Unfortunately we need to follow the vanilla naming right now due to how HTML and other frameworks handle the change event.

So, if you change `onRuxchange={this.onChange}` to `onRuxinput={this.onChange}`, it will work properly.
Here is a [forked version of your sandbox](https://codesandbox.io/s/xenodochial-firefly-3m82z?file=/src/App.js) as an example.

Thanks for bringing this up!

**Comment by 321github123** [comment]
That solves it - thanks!!!

From: Micah Jones ***@***.***>
Sent: Tuesday, November 9, 2021 12:47 PM
To: RocketCommunicationsInc/astro ***@***.***>
Cc: Mark Lai ***@***.***>; Author ***@***.***>
Subject: [Ext] - Re: [RocketCommunicationsInc/astro] RuxInput react component does not immediately update with state change (Issue #105)

CAUTION: Originated outside of IS4S.


Hey there,

The issue here is that onRuxchange doesn't fire until focus is lost, as per the vanilla functionality of the HTML change event<https://usg02.safelinks.protection.office365.us/?url=https%3A%2F%2Fdeveloper.mozilla.org%2Fen-US%2Fdocs%2FWeb%2FAPI%2FHTMLElement%2Fchange_event&data=04%7C01%7C%7C677d15320d5b42cf79f508d9a3b15a28%7Ced7b1ca07d8e4acbac42830a688573ae%7C0%7C0%7C637720804407377470%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0l2zSHWTcajlGL4SL1NyLyhPFQnf6Ae%2Bewd8AxK6ggY%3D&reserved=0>. This is opposite in React, where onChange fires with each user input<https://usg02.safelinks.protection.office365.us/?url=https%3A%2F%2Freactjs.org%2Fdocs%2Fdom-elements.html%23onchange&data=04%7C01%7C%7C677d15320d5b42cf79f508d9a3b15a28%7Ced7b1ca07d8e4acbac42830a688573ae%7C0%7C0%7C637720804407377470%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Eo0Ff%2FtzfsyBr5e681VPUp24Et7PlAa1FvFI6vMdg30%3D&reserved=0>.
Unfortunately we need to follow the vanilla naming right now due to how HTML and other frameworks handle the change event.

So, if you change onRuxchange={this.onChange} to onRuxinput={this.onChange}, it will work properly.
Here is a forked version of your sandbox<https://usg02.safelinks.protection.office365.us/?url=https%3A%2F%2Fcodesandbox.io%2Fs%2Fxenodochial-firefly-3m82z%3Ffile%3D%2Fsrc%2FApp.js&data=04%7C01%7C%7C677d15320d5b42cf79f508d9a3b15a28%7Ced7b1ca07d8e4acbac42830a688573ae%7C0%7C0%7C637720804407377470%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0Yo8RWt63c7b6a3IipEC9ojCEEiLjkKuanCqIRx7vYQ%3D&reserved=0> as an example.

Thanks for bringing this up!

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://usg02.safelinks.protection.office365.us/?url=https%3A%2F%2Fgithub.com%2FRocketCommunicationsInc%2Fastro%2Fissues%2F105%23issuecomment-964434010&data=04%7C01%7C%7C677d15320d5b42cf79f508d9a3b15a28%7Ced7b1ca07d8e4acbac42830a688573ae%7C0%7C0%7C637720804407377470%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GNu4o8evPqIbr3iI55hsLfA7vyq%2B9sJ%2FRjcIPHr7Wiw%3D&reserved=0>, or unsubscribe<https://usg02.safelinks.protection.office365.us/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWNHCGQFTM5TADZZWORDJMTULFUDHANCNFSM5HV7GF7A&data=04%7C01%7C%7C677d15320d5b42cf79f508d9a3b15a28%7Ced7b1ca07d8e4acbac42830a688573ae%7C0%7C0%7C637720804407377470%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8IGMbQvBwO1U%2BTRMrqzBmE%2FmVOP651aOR3515mmOvps%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://usg02.safelinks.protection.office365.us/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C677d15320d5b42cf79f508d9a3b15a28%7Ced7b1ca07d8e4acbac42830a688573ae%7C0%7C0%7C637720804407377470%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xksF2E7I68sObuanejzddQwPddofxZE8QrG9ROlhoyc%3D&reserved=0> or Android<https://usg02.safelinks.protection.office365.us/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C677d15320d5b42cf79f508d9a3b15a28%7Ced7b1ca07d8e4acbac42830a688573ae%7C0%7C0%7C637720804407377470%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tUQ6UOeWa4aEzFwIv7atLoRnOOjx6p%2BJa%2BQ9Raq8kzo%3D&reserved=0>.

_____________________________________
The information contained in this e-mail and any attachments from Integrated Solutions for Systems may contain confidential and/or proprietary information, and is intended only for the named recipient to whom it was originally addressed. If you are not the intended recipient, any disclosure, distribution, or copying of this e-mail or its attachments is strictly prohibited. If you have received this e-mail in error, please notify the sender immediately by return e-mail and permanently delete the e-mail and any attachments.
