### ISSUE TITLE
Support multiple items in the same Timeline Track

### ISSUE THREAD

**Issue by bjclarkLM** [RocketCommunicationsInc/astro#1069]
We have an user requirement that multiple independent bars been shown in the same track in the Timeline.  Each region would have an unique non-lapping start/end time.

**Comment by bjclarkLM** [comment]
Yes - I will send along something today

**Comment by bjclarkLM** [comment]
[Tracks.pdf](https://github.com/RocketCommunicationsInc/astro/files/10723060/Tracks.pdf)

**Comment by markacianfrani** [comment]
thanks for sending that over. is this example what you're looking to achieve? https://codepen.io/rocketmark/pen/jOvNpER

**Comment by bjclarkLM** [comment]
Yes this was exactly what we were looking for.  Thanks for the assist!
