### ISSUE TITLE
Rux-option disabled attribute not working properly

### ISSUE THREAD

**Issue by nortonprojects** [RocketCommunicationsInc/astro#1075]
**Describe the bug**
The `rux-option` disabled attribute doesn't respond reactively until the next change of the select.

**To Reproduce**
Jonathan Neal
It appears as tho the option is dynamic, but the change doesn’t take effect until the next change of the select.

Jonathan Neal
I tested this by creating a select with 3 options.
I dynamically disabled the 3rd option and it did not appear to be disabled.
I selected the 2nd option and the 3rd option immediately appeared disabled.

**Current behavior**
Dynamically changing the disabled state doesn't take effect immediately

**Expected behavior**
Dynamically changing the disabled state should be reflected in the select menu

**Environment (please complete the following information):**

- @astrouxds/astro-web-components 7.0.0
- Observed in Angular, with Angular wrapper, as well as vanilla AstroUXDS

**Additional context**
Jonathan Neal
I did try to trigger a few events like _handleLabelSlotChange() and _handleSlotChange() on the select, but they had no effect.

Jonathan Neal
Actually, manually triggering select._handleSlotChange() seems to update the visual state.

**Comment by micahjones13** [comment]
This will be fixed in todays release with version 7.8.
