### ISSUE TITLE
How do you give focus to a rux-input?

### ISSUE THREAD

**Issue by griley02** [RocketCommunicationsInc/astro#1085]
Say I'm displaying a dialog with a form and I want to give focus to the first rux-input shown so that the user can start typing into the field immediately, how do I do that?  I'm using Vue 3.x and the Astro web components.

**Comment by markacianfrani** [comment]
thanks for raising this issue. there were a few small issues preventing you from doing this that will be released in astro 7.9 this thursday. 

here's a quick example 

https://codesandbox.io/s/vue-focus-kds5q6?file=/src/App.vue

In short, you'll want to listen to the `ruxDialogOpened` event and then set focus on the input after it's been opened. 

There's currently an issue where the event will get fired before the content is available. The example gets around this by adding a setTimeout, but this will be fixed on thursday. 

The other issue in this example is that rux-input is missing a way to set focus programatically. In 7.9, we'll be adding a new `setFocus` method for that. 

I'll update that example after 7.9

**Comment by griley02** [comment]
Thank you for addressing this so quickly, I appreciate it!

**Comment by markacianfrani** [comment]
we've just released 7.9.0 with the new setFocus methods. here's an updated example https://codesandbox.io/s/astro-7-9-vue-focus-kds5q6?file=/src/App.vue feel free to reach out if you have any issues!
