### ISSUE TITLE
rux-option-group won't allow value to be pre-selected on render

### ISSUE THREAD

**Issue by david-1-kang** [RocketCommunicationsInc/astro#1125]
**Describe the bug**
A pre-selected value that's in the rux-option-group is not selected for any rux-option generated by an ngFor in a rux-option-group. If the <rux-option-group></rux-option-group> is removed and the rux-option is still generated by an ngFor then the pre-selected value is returned in the rux-select.

**To Reproduce**

Using the example on the Astro UXDS (https://astro-components.netlify.app/?path=/docs/forms-select-menu--select-menu) for rux-select with option groups; instead of individual rux-options in each group, use a ngFor to generate the same options. If a value that's in the rux-option-group is pre-selected, that value is not returned -- it defaults to the first rux-option outside of the rux-option-groups.

**Current behavior**
A pre-selected value that's in the rux-option-group is not returned after render.

**Expected behavior**
A pre-selected value that's in the rux-option-group is returned after render.

**Comment by micahjones13** [comment]
Hey @david-1-kang, thanks for opening this! I'm attempting to reproduce the issue in a [codesandbox](https://codesandbox.io/s/astro-angular-select-6nfozl) but haven't been able to yet. If you wouldn't mind, could you take a look and see if anything can be changed to better match your environment? Which version of `@astrouxds/angular` are you using?

**Comment by david-1-kang** [comment]
> Hey @david-1-kang, thanks for opening this! I'm attempting to reproduce the issue in a [codesandbox](https://codesandbox.io/s/astro-angular-select-6nfozl) but haven't been able to yet. If you wouldn't mind, could you take a look and see if anything can be changed to better match your environment? Which version of `@astrouxds/angular` are you using?

hey @micahjones13 , thank you for your reply -- the angular version we're using is 7.9.2 but we have upgraded recently to the newest release
to help replicate your issue, i modified your sandbox code -- here's the html and typescript files you need to better understand the issue

[example-html.txt](https://github.com/RocketCommunicationsInc/astro/files/11398537/example-html.txt)
[example-typescript.txt](https://github.com/RocketCommunicationsInc/astro/files/11398538/example-typescript.txt)

**Comment by micahjones13** [comment]
Hey @david-1-kang, thanks to your example we identified the issue and have released a fix. The fix is in the latest release (7.10.0). 
Thanks for bringing this up and for providing such good context! Please reach out if you encounter any other issues.
