### ISSUE TITLE
(React) SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by jm-bh** [RocketCommunicationsInc/astro#1174]
**Describe the bug**
When importing components into a Next.js (React framework) app, Astro throws `SyntaxError: Unexpected token 'export'`.

**To Reproduce**

1. Create a new Next app `yarn create next-app`
2. Install Astro `yarn add @astrouxds/react`
3. Add the CSS in `pages/_app.tsx` 
4. Use an Astro component on any page
5. Error

**Current behavior**
While rendering, a `SyntaxError` is thrown. 
The error comes from `@astrouxds/react/dist/index.js:1`: `export * from "./components";`

**Expected behavior**
No error

**Screenshots**
![image](https://github.com/RocketCommunicationsInc/astro/assets/138606233/bca11a49-3e55-4896-8c32-5a552bf4ab7d)
![image](https://github.com/RocketCommunicationsInc/astro/assets/138606233/020eb4db-1e4e-4ae8-b3a5-3f90484dbef7)

**CodeSandbox**
[View the problem on StackBlitz](https://stackblitz.com/edit/astro-nextjs-repro?file=pages%2Findex.tsx)

**Environment (please complete the following information):**

- Browser [e.g. chrome, safari]: **Chrome 114.0.5735.199 (Official Build) (64-bit)**
- @astrouxds/astro-web-components version [e.g. 7.0.0]: **7.13.0**
- Framework, if applicable (React, Angular, Vue, Svelte, ect): **Next.js (React)**
- Framework wrapper version, if applicable (@astrouxds/react or @astrouxds/angular): **@astrouxds/react**

**Additional context**
n/a

**Comment by jm-bh** [comment]
Turns out this is an issue with Next.js, not Astro.
Sorry about that!

For anyone else that runs into this issue, you need to use the `transpilePackages` option in `next.config.js`:

```js
{
  ...

  transpilePackages: [
    '@astrouxds/react',
    '@astrouxds/astro-web-components',
  ],
}
```

**Comment by micahjones13** [comment]
That's a good gotcha, we'll throw that in our docs. Thanks for letting us know!
