### ISSUE TITLE
Rux-log filtering is case sensitive

### ISSUE THREAD

**Issue by NicDominguez** [RocketCommunicationsInc/astro#1203]
**Describe the bug**
The rux-log component filtering of event.message is case sensitive contrary to the documentation and intended functionality. 

**To Reproduce**
Bug present on storybook component page.
https://astro-components.netlify.app/?path=/docs/components-log--log

**Current behavior**
Case sensitive filtering

**Expected behavior**
Case insensitive filtering

**Comment by micahjones13** [comment]
This has been fixed and will be released on Thursday (08/17) with version 7.16.
