### ISSUE TITLE
React boolean/removable prop issues

### ISSUE THREAD

**Issue by mrclean-oa** [RocketCommunicationsInc/astro#121]
I have to say this is a great library! Thank you for maintaining it. 

I have been working with the [React flavor](https://www.npmjs.com/package/@astrouxds/react) of the web component library, and have noticed some odd things around boolean/removable props. As an example, when the `RuxNotification` is in an open state, the HTML looks like this:

```html
<rux-notification status="standby" message="This is a notification banner. It won’t disappear until the user dismisses it." class="hydrated" open=""></rux-notification>
```

When it is a closed state:

```html
<rux-notification status="standby" message="This is a notification banner. It won’t disappear until the user dismisses it." class="hydrated"></rux-notification>
```

Notice that the `open` attribute is now completely missing. React does this natively with built-in elements like `input` with the `disabled` attribute. Because of this, it's most intuitive for React developers to do something like:

```jsx
<input disabled={isDisabled} />
```

But for some reason, any boolean attributes on `Rux*` components don't function the way you would expect when toggling the attribute. So I have developed this utility to help alleviate the issues as a _workaround_ but raising this issue in hopes for a more permanent fix:
```typescript
export function ruxBooleanHelper(
  condition: boolean,
  prop: string
): Record<string, boolean> {
  if (condition && prop) {
    return { [prop]: true };
  }
  return {};
}
```

I would expect to be able to toggle a boolean like `showNotification`, as an example, on the `RuxNotification` component:
```jsx
<RuxNotification open={showNotification} ... />
```
I think this needs to be solved for all `Rux*` components, since I think all boolean-related props will suffer from this. Ideally, they should function like toggling `disabled` on an input element.

Please let me know how I can help with this issue. Mark has my Email, or please mention me here.

**Comment by micahjones13** [comment]
Hey @mrclean-oa, we've merged in a fix for the react boolean prop issues. It'll be available in the next publish, which will happen early next year.
