### ISSUE TITLE
`<RuxTooltip />` renders block-level children taller than inline children

### ISSUE THREAD

**Issue by jm-bh** [RocketCommunicationsInc/astro#1216]
**Describe the bug**
Block-level elements inside a `<RuxTooltip />` make the tooltip taller than it should be.

**To Reproduce**

1. Create a `<RuxTooltip />`
2. Add a block-level element
3. Observe incorrect height

**Current behavior**
The tooltip is significantly taller than its children.

**Expected behavior**
The tooltip should not be taller than its children. (Inline elements still show the correct height.)

**Screenshots**
![image](https://github.com/RocketCommunicationsInc/astro/assets/138606233/653d04d8-ec1a-4c22-beed-84f36b0b26b3)
![image](https://github.com/RocketCommunicationsInc/astro/assets/138606233/81b80029-8376-40c8-82a0-b1a9b1ab81b4)

**CodeSandbox**
[StackBlitz](https://stackblitz.com/edit/astro-nextjs-repro?file=components%2FTable.tsx) (`/components/table`, line 72)

**Environment (please complete the following information):**

- Browser [e.g. chrome, safari]: **Chrome 115.0.5790.171**
- @astrouxds/astro-web-components version [e.g. 7.0.0]: **7.15.2**
- Framework, if applicable (React, Angular, Vue, Svelte, ect): **React**
- Framework wrapper version, if applicable (@astrouxds/react or @astrouxds/angular): **`@astrouxds/react`**

**Additional context**
Possibly related to #1188

**Comment by micahjones13** [comment]
Hey @jm-bh,
This issue has been fixed and will be included in today's release (7.16.0). Thanks for raising this!
