### ISSUE TITLE
RuxNotification unclosable from the "outside"

### ISSUE THREAD

**Issue by mrclean-oa** [RocketCommunicationsInc/astro#122]
Thank you for such a great component library that is easy to work with and provides awesome consistency right out of the box. Great work!

I wanted to pitch an enhancement to the `RuxNotification` [React flavor](https://www.npmjs.com/package/@astrouxds/react) of the component library. On the modal there is an event called `ruxmodalclosed` that gets fired when the modal closes. It would be helpful to have something like this for `RuxNotification`. Here's an example of why.

I have a use-case where I wanted to pop a notification—after talking with Mark it seems like the the new static banner component would be better, but this is what's available now, and maybe this will help inform the design of the static banner component. Anyway, I wanted to pop a notification when the user saved some data. So I had some code like this:

```jsx
//...
<RuxNotification open={isSuccess} message={messageFromServer} />
```

The problem is when the user clicks the `X` to close the notification, it starts closing then immediately shows again, because `open` is still `true`. So it would be more ideal to do something like:

```jsx
//...
<RuxNotification open={isSuccess} message={messageFromServer} onRuxnotificationclosed{() => setIsSuccess(false)} />
```

Then that event `ruxnotificationclosed` could fire once the `X` is clicked or once the `autoClose` has closed it programmatically. That would be a very useful enhancement, so that we can react to the user's interaction.

As a side note, I think that #121 is somewhat related, because even with this event, the boolean attribute of `open` won't function correctly when flipped.

**Comment by micahjones13** [comment]
Hey there, 

A `ruxclosed` event was added to notification in [this PR](https://github.com/RocketCommunicationsInc/astro/pull/120) however we forgot to reply back when it got merged, sorry! 
This is available now as of 6.0.5.

Sorry again for that delay!
