### ISSUE TITLE
Astro Storybook Site doesn't display components

### ISSUE THREAD

**Issue by danyelleabarnett** [RocketCommunicationsInc/astro#1285]
**Describe the bug**
On many of the pages for the Astro Storybook site, the components do not display.

**To Reproduce**

1. Go to https://astro-components.netlify.app/?path=/story/astro-uxds-start-here--page
2. Go to any of the component pages

**Current behavior**
None of the components appear on the storybook website

**Expected behavior**
Components should appear and be able to be interacted with

**Screenshots**
![image](https://github.com/RocketCommunicationsInc/astro/assets/158298620/c2f3b0b2-e668-424d-8eba-fa18a7cd098d)

**CodeSandbox**
N/A

**Environment (please complete the following information):**

- Browser: Chrome (Edge works)
- @astrouxds/astro-web-components version: N/A
- Framework: N/A
- Framework wrapper version: N/A

**Additional context**
N/A

**Comment by micahjones13** [comment]
Hey @danyelleabarnett, thanks for opening this! 

The icons page does take a bit to load due to the sheer number of icons - a faster alternative to view our icons is located here: https://www.astrouxds.com/icon-library/

I'm not seeing any components fail to load on my end. Were there any specific components you couldn't view?

**Comment by danyelleabarnett** [comment]
@micahjones13 Thanks for the quick response! This is every component that's affected. The team noticed them slowly disappearing over time, the icons were actually the last to disappear for us.

![image](https://github.com/RocketCommunicationsInc/astro/assets/158298620/62a4108b-dfaf-4784-a85d-025090c3f816)

**Comment by micahjones13** [comment]
Hey @danyelleabarnett, just wanted to follow up and see if your issue has been resolved or not. Hopefully whatever magic was preventing your team from seeing our components has since dispelled!

**Comment by danyelleabarnett** [comment]
@micahjones13 Thanks for following up! They showed up for a little while on Chrome shortly after we filed the issue, but they're back to being empty storybook pages again. Here's what the Console has:
![image](https://github.com/RocketCommunicationsInc/astro/assets/158298620/0df8e2ff-0396-4968-9102-7fe4fea32107)

**Comment by danyelleabarnett** [comment]
This appears to be working regularly now!
