### ISSUE TITLE
borderless icon only pressed bug

### ISSUE THREAD

**Issue by markacianfrani** [RocketCommunicationsInc/astro#1320]
**To Reproduce**
https://codepen.io/rocketmark/pen/rNgLvEJ

1. Hover over button
2. Click Button but hold mousedown
3. Hover away from button

**Current behavior**
Background/text change to blue

**Expected behavior**
Nothing changes (ideally we would have active/pressed states in the system but thats another topic)

**Screenshots**

https://github.com/RocketCommunicationsInc/astro/assets/1091342/b1dd075b-763f-4f99-9281-b3659f6859ad

**Environment (please complete the following information):**

- Chrome, Safari, Firefox
- Astro 7.22.1

**Comment by micahjones13** [comment]
@markacianfrani https://media.giphy.com/media/zaD3CladJIriYwmbj8/giphy.gif?cid=790b7611csjtretmezmvzy5o8lbzedej09y0uvptikk9p3ko&ep=v1_gifs_search&rid=giphy.gif&ct=g
