### ISSUE TITLE
rux-accordion behavior broken on chrome 131.0.6778.70

### ISSUE THREAD

**Issue by Taylorp913** [RocketCommunicationsInc/astro#1357]
**Describe the bug**
Rux-accordions are not behaving as expected in the docs as of the most recent version of chrome. The behavior is apparent on all astro apps that use rux-accordion and using chrome 131.0.6778.70.

**To Reproduce**

1. Install and open Chrome 131.0.6778.70
2. Go to https://grm-dashboard-react.netlify.app/
3. View degraded layout and behavior of rux-accordions in left hand pane

**Current behavior**
Accordions no longer span the container. Accordion content opens to the right of the accordion. 

**Expected behavior**
Accordions open below the accordion label. 

**Screenshots**
<img width="679" alt="Screenshot 2024-11-13 at 9 49 39 AM" src="https://github.com/user-attachments/assets/442867eb-afcd-4e36-a658-f851c405fa83">

**CodeSandbox**
If applicable, please provide a CodeSandbox or other online code editor tool link that contains an example of the bug.
https://grm-dashboard-react.netlify.app/

**Environment (please complete the following information):**

- Browser Chrome 131.0.6778.70
- @astrouxds/astro-web-components version [all]
- Framework, if applicable (all)
- Framework wrapper version, if applicable (all)

**Additional context**

**Comment by FMorrison87** [comment]
Hi Taylor, thanks for raising the issue. I just upgraded to the latest release of Chrome and I can reproduce the bug and I see what's causing it. We'll have a fix for this released as soon as we can.

**Comment by micahjones13** [comment]
Hey @Taylorp913, we have published version 7.24.1 which contains the fix for this issue. Thanks for bringing it up, and let us know if you need anything else!
