### ISSUE TITLE
Rux Clock Julian Date change is not accurate for UTC

### ISSUE THREAD

**Issue by mfryder** [RocketCommunicationsInc/astro#138]
When working with rux-clock, I noticed that the julian date change occurs between 1400-1700 UTC rather than at 0000UTC. Here are some screenshots from the story board:
Screenshots initially taken at Dec 2 2021 UTC:
![image](https://user-images.githubusercontent.com/5786681/144468059-37ba0baf-10c6-4878-bbc1-9861bc82a3d1.png)

Story Board Screenshot:
![image](https://user-images.githubusercontent.com/5786681/144468202-ba0587cf-2247-4e72-b46f-d06c65e11c3f.png)

I checked the morning of 12/2 and found that the Julian Date for the rux-clock changes around 14-16:00 UTC:
![image](https://user-images.githubusercontent.com/5786681/144468502-6b6933c7-7e88-4450-8e32-b0bc026d3e2f.png)

![image](https://user-images.githubusercontent.com/5786681/144468544-187d0a28-4725-4437-8426-b6dec280b6b2.png)

**Comment by markacianfrani** [comment]
thanks for raising this issue. we're looking into it now and will follow up here with more info

**Comment by markacianfrani** [comment]
quick status update--I've identified the problem. that date calculation is (incorrectly) going off of your local system timezone, not the timezone set on the clock component. I've got a fix, but we'll need a few more days for testing since this is such a mission critical component.

**Comment by mfryder** [comment]
Thanks for checking into this Mark!

**Comment by markacianfrani** [comment]
Sorry for the delay here. We've just published 6.0.5 which should resolve this. Let us know if you're still having issues
