### ISSUE TITLE
readonly attribute for RuxInput

### ISSUE THREAD

**Issue by jamesathey** [RocketCommunicationsInc/astro#157]
Ordinary `<input>` tags can be `readonly`, which is distinct from `disabled`. A `readonly` field cannot be edited by the user, but is still submitted with the form. A `disabled` field cannot be edited by the user, but is _not_ submitted with the form.

Please add the `readonly` attribute to `<rux-input>`, and apply that attribute to the underlying `<input>` when it is present.

**Comment by micahjones13** [comment]
Hey there,

Just an update that I am creating a pull request as we speak to add in the `readonly`, `spellcheck`, and `autocomplete` to RuxInput, and will comment again here when it's merged. 

Thank you for opening these issues!

**Comment by micahjones13** [comment]
Alrighty, the fix has been merged and will be included in the next minor version release early next year. Thanks!
