### ISSUE TITLE
Rux Status Bar does not allow Tooltips to display

### ISSUE THREAD

**Issue by tkrause** [RocketCommunicationsInc/astro#186]
We have a project using rux-status-bar with mission status icons. On hover, the icons need to show details of the actual status of the system.

However, the tooltips are not visible due to the `contain: content` class property applied to the rux-status-bar in the Shadow DOM. 

Proposed fix: 

Setting this property to `contain: layout` allows the tooltip to display and keeps the layout unchanged.

**Comment by micahjones13** [comment]
Hey there, 
The current version of rux-global-status-bar has `contain: layout` set. If the version you are one does not, you should be able to set it to layout by: `rux-global-status-bar { contain: layout }` since it's applied to the `:host`.
