### ISSUE TITLE
astro rux-clock component - day not advancing

### ISSUE THREAD

**Issue by aaronwink-rocket** [RocketCommunicationsInc/astro#289]
As shown in the image below, when the UTC time advances from 23:59:59 to 00:00:00, the date is not incrementing to the next day as it should. This bug was traced to the Astro rux-clock component: https://www.astrouxds.com/components/clock/.

<img width="474" alt="Screen Shot 2022-03-14 at 09 10 35" src="https://user-images.githubusercontent.com/81182419/158201985-f704913e-96f2-468c-b7b1-7eeac6bec9ae.png">

**Comment by markacianfrani** [comment]
@aaronwink-rocket I think this is for the old 5.3 components over at https://github.com/RocketCommunicationsInc/astro-components. We just published a patch for this. If you update `@astrouxds/rux-clock` to 5.3.1, this should be fixed now.

**Comment by markacianfrani** [comment]
closing, feel free to follow up if youre still having issues after 5.3.1
