### ISSUE TITLE
rux-input has additional space above the input box when no label is provided

### ISSUE THREAD

**Issue by QGerrit** [RocketCommunicationsInc/astro#372]
This causes it to not correctly line up alongside elements which do properly fully hide the label spacing when there is no label:

`<rux-input></rux-input>`

![image](https://user-images.githubusercontent.com/97202638/165149331-c3f9462f-cc76-4a34-9e95-c2bd88d5da1f.png)

`<rux-checkbox-group></rux-checkbox-group>`

![image](https://user-images.githubusercontent.com/97202638/165149461-6a1d7ee4-8525-4163-b1f3-3dc9843b2253.png)

**Comment by micahjones13** [comment]
Hey @QGerrit , a fix for this has just been merged and will be available in our release tomorrow (6.6). Thanks for bringing this up!
