### ISSUE TITLE
Feature Request: Add External Time prop to rux-clock

### ISSUE THREAD

**Issue by kaubster** [RocketCommunicationsInc/astro#384]
Add Prop _dateIn_ to rux-clock

_dateIn_ when supplied with a valid [date string or value](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#syntax) overrides Date.now() standard clock.

modify updateTIme() to update _time and localDate useing _dateIn_ (when provided) otherwise default back to Date.now().

**Comment by micahjones13** [comment]
Hey @kaubster, this feature has been merged in. Unfortunately the merge missed our release cadence by a few hours, so this feature will be available in the next release on the 26th.
Thanks for raising this!
