### ISSUE TITLE
Table breaks out of container

### ISSUE THREAD

**Issue by markacianfrani** [RocketCommunicationsInc/astro#390]
![Screen Shot 2022-05-06 at 3 31 45 PM](https://user-images.githubusercontent.com/1091342/167205350-daffb642-0195-4cb1-b7b5-f70f7d51121f.png)

Steps to reproduce:
https://codesandbox.io/s/table-bug-spdfml

Expected behavior:
It should behave like the native html table element. 

We should reevaluate if Table should even be a component because of how complicated and weird it is. Our implementation just wraps the native elements and applies very minor styling, which could be part of a separate opt in stylesheet. But our table has all of the disadvantages of display: table. In cases like this, its way easier to just write a <table>

**Comment by micahjones13** [comment]
Food for thought - a vanilla table with our design tokens is really easy to create now, thus adding to the argument for dropping RuxTable. Not sure there is enough utility or benefit being provided to warrant keeping it around.
