### ISSUE TITLE
Upgraded from from 6.0.8 to 6.8. Modal Window Not Displaying Correctly.

### ISSUE THREAD

**Issue by markacianfrani** [RocketCommunicationsInc/astro#419]
### Discussed in https://github.com/RocketCommunicationsInc/astro/discussions/418

<div type='discussions-op-text'>

<sup>Originally posted by **jldayhoff** May 27, 2022</sup>
Modal window does not display correctly after upgrading from 6.0.8 to 6.8. The buttons also do not have a border regardless of set to true or false. 

![image](https://user-images.githubusercontent.com/22620849/170787782-ae205dfb-f841-4366-a503-0541c2226d6b.png)
</div>

**Comment by micahjones13** [comment]
Wrong CSS file was being used - issue resolved
