### ISSUE TITLE
rux-pop-up-menu does not work well when browser is resized. 

### ISSUE THREAD

**Issue by tallen30** [RocketCommunicationsInc/astro#422]
When the browser(in this case firefox) is resized to be smaller than full screen and the rux-pop-up-menu button is selected, the possible choices in rux-menu-items are not displayed below the rux-pop-up-menu and are instead off to the side. See image below. 
<img width="457" alt="Rogue rux-pop-up-menu" src="https://user-images.githubusercontent.com/94630891/171262352-2916afad-b315-40b8-8d4d-1e60a3263b48.png">

**Comment by micahjones13** [comment]
Hey @tallen30 , could you provide the code used or a codesandbox that shows this issue? I'm having trouble reproducing it. It might also be helpful to know what version of astrouxds/astro-web-components you're using. Thanks!

**Comment by tallen30** [comment]
We are using version 6.6.0 of astrouxds/astro-web-components. I mocked up an example of the html below. This is just a basic title bar component that is presented when the application is opened. 

<rux-global-status-bar
  app-domain="Test"
  app-name="Application"
>
  <ul slot="right-side">
    <li>
      <rux-icon
        icon="settings"
        label="Settings"
        aria-controls="popup-menu-1"
      ></rux-icon>
      <p>Settings</p>
    </li>
  </ul>
</rux-global-status-bar>

<rux-pop-up-menu id="popup-menu-1">
  <rux-menu-item> Item 1 </rux-menu-item>
  <rux-menu-item disabled="">Item 2 is disabled</rux-menu-item>
  <rux-menu-item value="Item 3">Item 3 has a string value</rux-menu-item>
  <rux-menu-item href="https://www.astrouxds.com">Item 4 is an anchor/action item...</rux-menu-item>
</rux-pop-up-menu>

**Comment by tallen30** [comment]
It seems to happen when a horizontal scrollbar is in there. See sandbox [here](https://codesandbox.io/s/distracted-surf-6ibr9v?file=/index.html)
