### ISSUE TITLE
Support for type=time in rux-input

### ISSUE THREAD

**Issue by QGerrit** [RocketCommunicationsInc/astro#435]
`<rux-input type="time">` mostly works as expected (the icon gets shown in black), but it would be nice to have official support for it. [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time) says browser support is pretty good.

**Comment by micahjones13** [comment]
Ticket created! At first glance I don't think this will take much time to implement. Thanks again!

**Comment by micahjones13** [comment]
Hey @QGerrit this is now live in 6.9. Thanks!
