### ISSUE TITLE
RuxInput and RuxTextarea not responding to backspace key presses

### ISSUE THREAD

**Issue by EzraBrooks** [RocketCommunicationsInc/astro#535]
I'm using `@astrouxds/react`, at the latest version, and I can type into text fields but cannot use the backspace key. Strangely, the delete key works. Am I doing something wrong, or is this broken?

**Comment by micahjones13** [comment]
Hey @EzraBrooks, I'm so far unable to reproduce this issue. I've tried it out in this sandbox, https://codesandbox.io/s/hopeful-tamas-ptci99?file=/src/App.js - could you update that with an example of backspace not working if possible? Thanks!

**Comment by EzraBrooks** [comment]
It's definitely another library contaminating the global key handlers - `react-flow-renderer`. I'll open an issue there. Thanks for the quick response pushing me in the right direction.
