### ISSUE TITLE
Ability to use an icon in openlayers map

### ISSUE THREAD

**Issue by jduncanRadBlue** [RocketCommunicationsInc/astro#684]
I have an openlayers map and I'd like to be able to incorporate icons in the style properties of a feature.

Is there a way to accomplish this?

To use an icon openlayers suggests this way:

```
new Style({
          geometry: new Point(end),
          image: new Icon({
            color:'#FCCC34',
            src: arrow, //location of the icon file http://www.iconlocation.com/data/arrow.jpg OR could be local in asset folder
            anchor: [0.75, 0.5],
            rotateWithView: true,
            rotation: -rotation
          })
        })
```

Any help would be greatly appreciated!

**Comment by micahjones13** [comment]
Hey there,

From the looks of it, we just need to get you the icon path so you can use it in the `src` field. We unfortunately don't have our icons hosted anywhere easily accessible at the moment (it's on our to-do list though), but you can still find them if you dive into our repo on github. For example, [this link](https://github.com/RocketCommunicationsInc/astro/blob/main/packages/web-components/src/icons/satellite-transmit.svg?short_path=c708e7e) will get you to the source code for the satellite-transmit icon. From there, you should be able to copy that and store it locally to use in the src field.

I hope this helps! If it doesn't end up working, please let me know and I will explore some other solutions.

**Comment by micahjones13** [comment]
Hey @jduncanRadBlue, just wanted to follow up and see if you got this sorted or not. How's it going? Was the suggestion above helpful at all?
