### ISSUE TITLE
Placeholder for RuxInput and RuxTextArea are different colors in default dark theme

### ISSUE THREAD

**Issue by EzraBrooks** [RocketCommunicationsInc/astro#738]
Example:

<img width="435" alt="Screen Shot 2022-09-20 at 3 15 07 PM" src="https://user-images.githubusercontent.com/1959658/191366043-e1a8d222-146a-4161-a861-f89a2b55d4e4.png">

**Comment by micahjones13** [comment]
Hey there, 

Thanks for raising this issue! The fix has been merged and will be published with the next release.
