### ISSUE TITLE
RuxButton `disabled` property does not prevent `onClick` event

### ISSUE THREAD

**Issue by kit047** [RocketCommunicationsInc/astro#757]
I am utilizing `RuxButton` in React and when a button is `disabled`, the `onClick` event still fires when a user clicks it. The button does *look* disabled, so it is a bit jarring to have feedback upon a user click.

Note - a `RuxButton` of `type=submit` *does not* fire an `onSubmit` event from a parent form. This is working as expected.

**Comment by micahjones13** [comment]
Hey there,

I've tried reproducing this issue [here](https://codesandbox.io/s/disabled-rux-button-f24i5l?file=/src/App.js), but haven't had any luck. Could you take a look and see if you could reproduce it? It may also be helpful to know which versions of `@astrouxds/react` and React you are using. 

Thanks!

**Comment by kit047** [comment]
I believe you are correct - I was a few versions behind - `6.6.0`. I forgot we had locked the version a while back. Updating to `6.13.1` seemed to have fixed the issue I was seeing.

I will close the issue.

Thanks!
