### ISSUE TITLE
rux-pop-up (7.0.1) is hidden behind other elements

### ISSUE THREAD

**Issue by ascala07** [RocketCommunicationsInc/astro#812]
When a rux-pop-up in version 7.0.1 is opened and there are other elements nearby, the elements overlay on top of the pop up menu. I tried this with rux-inputs and rux-buttons. You can see this issue in [my sandbox](https://codesandbox.io/s/rux-pop-up-menu-hidden-6rftuy?file=/src/app/app.component.html).

**Comment by markacianfrani** [comment]
Thanks for raising this issue (and providing a sandbox)! We'll have a fix published in our next release next Thursday. In the meantime if this is blocking, you can apply this fix yourself using the `popup-content` CSS shadow part and setting a z-index:

```
rux-popup::part(popup-content) { 
  z-index: 100;
}
```

**Comment by ascala07** [comment]
That worked, thanks for the help. Would that release next Thursday be 7.0.2?

**Comment by markacianfrani** [comment]
we had a few other fixes pending so we just released 7.0.2 today with this fix in it. let us know if youre still having issues after upgrading
