### ISSUE TITLE
rux-textarea v7.0.1 can't be sized correctly

### ISSUE THREAD

**Issue by run2xs** [RocketCommunicationsInc/astro#814]
I have a rux-text-area in a div with a height of 700 pixels, but the rux-text-area will not render any larger than 72 pixels.  I've tracked the problem down to the rux-textarea-wrapper.  The following css is required to make the textarea larger than 72 pixels (this is from v6, and it worked fine there):

rux-textarea {
  height: 100%;
}
rux-textarea::part(form-field) {
  height: 100%;
}
rux-textarea::part(textarea) {
  resize: none;
  height: 100%;
}

However, in v7.0.1 there is now a div that surrounds the HTML textarea with a class of rux-textarea-wrapper.  I have to also set its height to 100% to get the text area to expand to the height of its parent div.

The problem is that there is no "part" attribute on that div, so I can't modify its height like the snippets I included above. 

Ideally, I shouldn't need to monkey around with all those part selectors in the first place.  Setting the height on the rux-textarea element should honor whatever height I want.  If you aren't going to allow that, please add a part attribute to the rux-textarea-wrapper so I can change the height of the textarea without resorting to Javascript shadow selector shenanigans.

![Screen_Shot_2022-10-06_at_2_43_54_PM](https://user-images.githubusercontent.com/1231788/194415060-8d145f83-b81e-4d1b-bde9-479921662531.jpg)

**Comment by run2xs** [comment]
Here is the only workaround I've found:

ngAfterViewInit() {
    setTimeout(() => {
      document.querySelector('#ruxTextarea').shadowRoot.querySelector('.rux-textarea-wrapper')['style'].height = '100%';
    }, 500);
  }

That is not acceptable.

**Comment by markacianfrani** [comment]
Thank you for raising this. I agree with you, that is totally not acceptable. 

> Ideally, I shouldn't need to monkey around with all those part selectors in the first place. Setting the height on the rux-textarea element should honor whatever height I want

I also 100% agree with you here. 

Short term: we're going to roll back that breaking change and release a 7.0.2 hotfix tomorrow. 

Long term: we'll investigate some options to improve the DX for resizing textareas.

**Comment by markacianfrani** [comment]
7.0.2 has been released and reverts textarea back to the v6 internals so your original code should work. let us know if you're still having issues.

thanks again for the feedback on how you're using parts to control the height. we're looking at that now. if you experience any other papercuts like these, please dont hesitate to open an issue.
