### ISSUE TITLE
Unable to turn off resize attribute on rux-textarea in v7.0.1

### ISSUE THREAD

**Issue by run2xs** [RocketCommunicationsInc/astro#815]
In v6, I was able to turn off the resize handle at the bottom right of the rux-textarea with the following:

rux-textarea::part(textarea) {
  resize: none;
}

That is not working, and I am unable to find a way to disable the resize handle on the textarea in v7.0.1.

**Comment by micahjones13** [comment]
With the above fix merged, using the shadow part to set `resize: none` works again in version 7.0.2. 
Thank you for raising this, we really appreciate it!
