### ISSUE TITLE
Scrollbar colors aren't working in Firefox in v7.0.2

### ISSUE THREAD

**Issue by run2xs** [RocketCommunicationsInc/astro#832]
Since upgrading to 7.0.2, I noticed in our app today that all the scrollbars and their backgrounds are gray in Firefox.  In some cases for non-rux components, the scrollbar is missing altogether.  I believe it's being caused by the 7.0.2 styling, because it works correctly in those components in Chrome.

You can see this on your own website [here](https://astro-components.netlify.app/?path=/story/components-icons--all-icons).

Chrome:

<img width="1070" alt="Screen Shot 2022-10-12 at 12 24 25 PM" src="https://user-images.githubusercontent.com/1231788/195420737-d9ce190e-e2cc-46fd-a80e-738a4243e82f.png">

Firefox:

<img width="766" alt="Screen_Shot_2022-10-12_at_12_24_17_PM" src="https://user-images.githubusercontent.com/1231788/195420796-8234e031-aa83-447a-9bc3-3dec2c75eea0.png">

**Comment by micahjones13** [comment]
This will be fixed in the release tomorrow with version 7.0.3. Thanks for raising this!
