### ISSUE TITLE
Popup menu sometimes doesn't close when close-on-select property is set

### ISSUE THREAD

**Issue by run2xs** [RocketCommunicationsInc/astro#839]
@micahjones13 Thanks for adding the close-on-select property to the rux-pop-up.  The popup menu will close correctly if my menu item action navigates to a different route.  This did not work before, so it's an improvement.  However, I have another menu item that just changes the light/dark theme by changing the class on the body element.  When I choose this one, the menu item does not close.

**Comment by markacianfrani** [comment]
do you mind pasting just your markup (or some minimal version of it) so we can get a better idea of your use case?

**Comment by run2xs** [comment]
Here's an edited version of the HTML:

`<rux-global-status-bar include-icon="false" appName="{{xx}}" appVersion="{{xxx}}">
  <rux-pop-up #ruxPopUp close-on-select id='xxx-popup-menu' slot='left-side'>
    <rux-icon slot='trigger' size="small" icon="apps" aria-controls="xxx-popup-menu"></rux-icon>
    <rux-menu>
      <rux-menu-item *ngFor='let navPage of navPages' (click)='navigateTo(navPage.route)'>{{navPage.label}}</rux-menu-item>
      <rux-menu-item-divider></rux-menu-item-divider>
      <rux-menu-item *ngIf="isDarkTheme" (click)='changeTheme()'>Set Light Theme</rux-menu-item>
      <rux-menu-item *ngIf="!isDarkTheme" (click)='changeTheme()'>Set Dark Theme</rux-menu-item>
      <rux-menu-item-divider *ngIf="(isAuthenticated | async) && isAuthEnabled"></rux-menu-item-divider>
      <rux-menu-item (click)='logout()'>Logout</rux-menu-item>
    </rux-menu>
  </rux-pop-up>
  <atlas-ui-system-mode></atlas-ui-system-mode>
  <rux-clock timezone='UTC'></rux-clock>
</rux-global-status-bar>`

Here's the call that doesn't close the popup:

` changeTheme() {
    this.isDarkTheme = !this.isDarkTheme;
    const themeColorClass = this.isDarkTheme ? 'dark-theme' : 'light-theme';
    document.body.className = themeColorClass;
    //todo: remove this when Astro fixes the close bug
    this.ruxPopUp['el'].hide();
  }
`

**Comment by run2xs** [comment]
Not sure why I'm losing all the formatting above.  I'm attaching a file with the same content.

[astro.txt](https://github.com/RocketCommunicationsInc/astro/files/9812698/astro.txt)

**Comment by markacianfrani** [comment]
Thanks for raising this! I think this issue is partly due to Angular's change detection and your use of ngIf. We'll need some more time to explore if there any changes we can make to the component so that you don't have to change your implementation. Since the `hide` method gives you a workaround, we're going to deescalate this a bit but I'm going to keep the issue open. In the meantime, let us know if you keep encountering this problem in other places

**Comment by markacianfrani** [comment]
We definitely took our time on this one. We weren't able to come up with any built in solutions for this component specifically but are investigating some more open alternatives for future releases.
