### ISSUE TITLE
React - Rux-Tabs not clearing default selected

### ISSUE THREAD

**Issue by Full-lifey** [RocketCommunicationsInc/astro#844]
When using Rux Tabs we are selecting a default value by using the selected prop on `RuxTab`.

However, when we do that there is a bug where clicking on the other tab doesn't clear the selected state from the first tab when clicking it for the first time.

NOTE: This only seems to happen when also adding an `onClick` handler to the `RuxTabs` component.

An example can be found here:
https://codesandbox.io/s/gifted-cache-ntdj78

**Comment by micahjones13** [comment]
Issue solved internally with Maria - closing now.
