### ISSUE TITLE
rux-menu-item href not working in 7.1.0

### ISSUE THREAD

**Issue by aubsparrow** [RocketCommunicationsInc/astro#862]
We had a rux-menu with some rux-menu-items that were links to other pages in our app. This worked in 6.13, but with the upgrade to 7.1 the links no longer work. 

`<rux-pop-up placement="bottom-end" id="global-menu">
            <rux-icon icon="apps" slot="trigger"></rux-icon>
            `<rux-menu>`
                <rux-menu-item href="rkm.html">Home</rux-menu-item>
                <rux-menu-item href="node_diagram.html">Node Diagram</rux-menu-item>
                <rux-menu-item href="edit_thing.html">Create New Entry</rux-menu-item>
                <rux-menu-item-divider></rux-menu-item-divider>
                <rux-menu-item id="change-theme" value="change-theme">Change Theme</rux-menu-item>
            </rux-menu>
        </rux-pop-up>`

**Comment by markacianfrani** [comment]
Thanks for raising this! This was an undocumented 7.0 change, but we've gone ahead and reverted it so you won't need to change anything. We should have this fix out in our next release on 11/10
