### ISSUE TITLE
rux-time-region is missing styling for status 'serious'

### ISSUE THREAD

**Issue by GPierceJr** [RocketCommunicationsInc/astro#885]
**Describe the bug**
The template for rux-time-region references .rux-time-region--serious, which does not exist in the scss file (but should).

**To Reproduce**

Create a rux-time-region with status="serious".

**Current behavior**
rux-time-regions with status="serious" have the correct status icon but the default border color

**Expected behavior**
rux-time-regions with status="serious" should have both the correct status icon and an orange border

**Environment (please complete the following information):**

- Any browser
- @astrouxds/astro-web-components version 7.0.2
- Angular
- @astrouxds/angular version 7.0.2

**Comment by micahjones13** [comment]
This has been fixed in the above PR, along with the addition of the 'off' status as an option on rux-time-region. Thanks for opening this issue! The fix will be released on 11/10.
