### ISSUE TITLE
rux-input displaying "Start typing to search" dispite using ruxchange or ruxinput

### ISSUE THREAD

**Issue by raven2500** [RocketCommunicationsInc/astro#960]
**Describe the bug**
With a rux-input field both ruxchange and ruxinput were used to try to prevent the user from entering a / character, which MS Edge treats as a search.   We are preventing the entry of the / character, but sometimes the resulting "Start typing to search" dialog still opens, but not all of the time.   

**To Reproduce**

See Description above

**Current behavior**
See Description above

**Expected behavior**

**Screenshots**

**CodeSandbox**
If applicable, please provide a CodeSandbox or other online code editor tool link that contains an example of the bug.

**Environment (please complete the following information):**

- @astrouxds/astro-web-components version [e.g. 7.0.0]
- Framework, if applicable (React, Angular, Vue, Svelte, ect)
- Framework wrapper version, if applicable (@astrouxds/react or @astrouxds/angular)

**Additional context**

**Comment by micahjones13** [comment]
Closing as stale
