### ISSUE TITLE
Progress component looks strange with value = 1

### ISSUE THREAD

**Issue by thdoan** [RocketCommunicationsInc/astro#985]
**Describe the bug**
When the Progress component has a value of 1, the "completed" portion doesn't look good.

**To Reproduce**

1. Go to https://astro-components.netlify.app/?path=/story/components-progress--default-story
2. See the issue

**Current behavior**
The "completed" portion looks like a pill.

**Expected behavior**
The "completed" portion should look more like it's part of the progress bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/4110567/207680575-a7e5d1e3-6b49-4259-9227-9ba35e934ad0.png)

**Environment (please complete the following information):**

- Browser: Chrome 108.0.5359.99
- @astrouxds/astro-web-components version: whatever version is powering astro-components.netlify.app right now

**Comment by kiley-mitti** [comment]
Hi @thdoan Thanks for bringing this to our attention! I'm going to put in a ticket and bring this up with our design team. I will keep you updated.

**Comment by markacianfrani** [comment]
this issue has been fixed in our 7.7.0 release
