### ISSUE TITLE
Textarea component scrollbar is inconsistent with design

### ISSUE THREAD

**Issue by thdoan** [RocketCommunicationsInc/astro#986]
**Describe the bug**
The Textarea component's scrollbar doesn't have the same style as scrollbars in other components.

**To Reproduce**

1. Go to https://astro-components.netlify.app/?path=/story/forms-textarea--default-story
2. Press Enter inside the textarea field until you see a scrollbar
3. See issue

**Current behavior**
The Textarea's scrollbar looks like a native browser scrollbar (unstyled).

**Expected behavior**
The scrollbar should have the same style as seen in other components, like the one in the screenshot below.

**Screenshots**
![image](https://user-images.githubusercontent.com/4110567/207685565-fa80842b-2a0f-4d8f-b85a-21bccdca582b.png)

**Environment (please complete the following information):**

- Browser: Chrome 108.0.5359.99
- @astrouxds/astro-web-components version: not sure, whatever is on astro-components.netlify.app right now

**Comment by kiley-mitti** [comment]
Hi @thdoan, thanks so much for pointing this out! We've added the proper styling for textarea scrollbars, bringing them inline with Astro styling. These changes will be available in our next patch release Thursday, Dec. 22nd.
